#version: '3.7'
#services:
#  db:
#    image: mysql
#    container_name: meu_mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#    ports:
#    - "3306:3306" # primeira porta do localhost segunda porta do docker (container docker, talvez)
#    volumes:
#    - devdojo_data:/var/lib/mysql
#
#volumes:
#  devdojo_data:
