server:
  error:
    include-stacktrace: on_param

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/sales-control-db?createDatabaseIfNotExist=true
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
##    show-sql: true
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: create #validate, update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
      enabled: true
      path: /h2
