server:
  error:
    include-stacktrace: never

#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    class-driver-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#      path: /h2

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-essentials2-db?createDatabaseIfNotExist=true
    username: root
    password: root
    class-driver-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect