server:
  error:
    include-stacktrace: never

#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    class-driver-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#      path: /h2

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-essentials2-db
    username: sa
    password:
    class-driver-name: org.mysql.Driver
  h2:
    console:
      enabled: true
      path: /h2