#server:
#  error:
#    include-stacktrace: never
#
#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    class-driver-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#      path: /h2