spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: smtp.gmail.com
    port: 587
    test-connection-false: false
    username: toribayahto@gmail.com
    passwod: no-have
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

support:
  mail: toribayahto@gmail.com

server:
  error:
    include-stacktrace: on_param